Bryan's Work
CenterForDigitalHumanities/deer pull request #113
Opened 2022-09-21 00:49 UTC by thehabes

2022-09-21 02:31 UTC, thehabes commented
So this works now, but it probably doesn't help you.  Maybe I hit it just hard enough, maybe it's dead.  IDK man, this whole thing felt like an Alice in Wonderland special.

2022-09-21 02:36 UTC, thehabes commented
Oh boy, index.html appears to work too.  LOLZ.THEN(drink=>beer())

2022-09-21 14:19 UTC, cubap requested changes

2022-09-21 14:19 UTC, cubap commented on components/view/view.js
> +UTILS.worker = await import("../../js/worker.js").then(module => {return module.default}).catch(err => {return {"error":err}})
This "works" but it is not a `Worker` like `UTILS.worker = new Worker("worker.js'',{type:"module"})` but it may be just fine.

2022-09-21 14:19 UTC, cubap commented on js/deer-record.js
> +UTILS.worker = await import("./js/worker.js").then(module => {return module.default}).catch(err => {return {"error":err}})
This can't import on UTILS? This will make a mess if we have to do it this way...

2022-09-21 14:19 UTC, cubap commented on js/deer-utils.js
> +    //"worker" : import("./worker.js").then(module => {return module}).catch(err => {return {"error":err}}),
This is a big loss.

2022-09-21 14:19 UTC, cubap commented on js/deer-utils.js
> +        import("./worker.js").then(module => {module.default.postMessage(message)}).catch(err => {return {"error":err}})
... I cannot accept this.

2022-10-03 14:28 UTC, thehabes commented
Closing with honors.  It served its purpose well.

2022-10-03 14:28 UTC, closed without merging