127 improve json template
CenterForDigitalHumanities/deer pull request #138
Opened 2023-11-06 16:11 UTC by Regorh

Code has been added allowing users to download text present in JSON templates to their machine as a text file.  JSON template border and background coloring has been improved as well. A "copy" button could also be added at some point.

2023-11-13 17:06 UTC, thehabes requested changes
The button should be small and as out of the way as possible.  Instead of an actual button with text, consider using a symbol instead like https://icongr.am/feather/download.svg.  You can use a tooltip if you want it to have some text.

You did not consider how the button would affect text that is long enough to overflow.

![image](https://github.com/CenterForDigitalHumanities/deer/assets/3287006/2b4e8458-bda7-4af1-a6ca-94b76b78fd0b)

You will have to think harder about positioning and make it so that the button is never in the way of text.

2023-11-13 17:06 UTC, thehabes commented on test.html
> +<html>
Thanks for committing this in so I could see how you were testing.  Just remember that this file should not be in the finalized PR for `main` and should only exist in your Draft PR.  Please remove this file.

2023-11-13 17:06 UTC, thehabes commented on js/deer-render.js
> +    let indent = options.indent || 4;
Get rid of semicolons.

2024-10-18 05:58 UTC, cubap requested changes
Closing as unfinished though some useful parts are in here

2024-10-18 05:58 UTC, closed without merging